### PR TITLE
Fix Imports to point to the actual symbols rather then wrongly imported ones

### PR DESCRIPTION
**Pull request by stefan-koch-sociomantic**
There were a few imports which were taken from modules which are not the modules were they are defined in.

This PR fixes that.

### CODE REVIEW

**Comment by wilzbach** [comment]
This fails with:

```
22 Feb 2018 02:04:35.050220 <190>1 2018-02-22T01:04:34.801751+00:00 app web.1 - - [C6EBDFDE:C1DB8FDE ERR] PUT https://api.github.com/repos/dlang-community/dfmt/pulls/334/merge failed; Method Not Allowed 405.
22 Feb 2018 02:04:35.050187 <190>1 2018-02-22T01:04:34.801847+00:00 app web.1 - - [C6EBDFDE:C1DB8FDE dbg] Failed to handle the complete response of the server - disconnecting.
```

I assume it's due to the new branch settings?
@leandro-lucarella-sociomantic are you keen on keeping all of them? Seems like the bring more pain than they are worth.

**Comment by stefan-koch-sociomantic** [comment]
@wilzbach We use rebase instead of merge to avoid polluting the history.

**Comment by stefan-koch-sociomantic** [comment]
@Hackerpilot or @wilzbach can you pull/rebase this ?

**Comment by leandro-lucarella-sociomantic** [comment]
> I assume it's due to the new branch settings?
> @leandro-lucarella-sociomantic are you keen on keeping all of them? Seems like the bring more pain than they are worth.

We can do that if there is no way around, but would like very much to be able to rebase PRs instead of merging, as Stefan said, to keep the history sane (specially when inspected via `gitk` or `git log --graph`). We hoped the bot was just using whatever default method for merging is available.

Ah, I see there is no default option for `merge_method` in the API. How hard would it be to add a `auto-rebase` tag to use the `rebase` method instead? Or maybe to just try all the methods and only fail if none of them work?

**Comment by leandro-lucarella-sociomantic** [comment]
> @Hackerpilot or @wilzbach can you pull/rebase this ?

I will wait for the feedback on the `auto-merge` feature before using the `rebase` button.

**Comment by wilzbach** [comment]
> Ah, I see there is no default option for merge_method in the API. How hard would it be to add a auto-rebase tag to use the rebase method instead? Or maybe to just try all the methods and only fail if none of them work?

`auto-merge-rebase` already works today - one just needs to add the button (I just did so).
Though it still fails with:

```
PUT https://api.github.com/repos/dlang-community/dfmt/pulls/334/merge failed; Method Not Allowed 405.
```

That's typically a permission problem with too restrictive branch settings.

**Comment by wilzbach** [comment]
> That's typically a permission problem with too restrictive branch settings.

Yep, it was.

> We can do that if there is no way around, but would like very much to be able to rebase PRs instead of merging, as Stefan said, to keep the history sane (specially when inspected via gitk or git log --graph). 

I don't see the point, and I especially like "auto-merge-squash", but if you want to avoid that other people use the normal merge, simply remove the "auto-merge" and "auto-merge-squash" labels. That's all that's required.

**Comment by leandro-lucarella-sociomantic** [comment]
> auto-merge-rebase already works today - one just needs to add the button (I just did so).

Ah, great!

> That's typically a permission problem with too restrictive branch settings.

Was this solved then now?

> I don't see the point, and I especially like "auto-merge-squash", but if you want to avoid that other people use the normal merge, simply remove the "auto-merge" and "auto-merge-squash" labels. That's all that's required.

Squashing merge is completely different, I don't want to squash all the commits of a PR (like ever) and lose the history. This is why we just disable both types of merges (normal merges and squash merges).

I know this is a bikeshed problem. On some specific cases the tool we use for release assumes merges are only used to merge a release on development branches, so allowing regular merges could be problematic. If it's important for you to support both we can talk about it but for now it will be safer if we just allow only rebase merges.

**Comment by wilzbach** [comment]
> Was this solved then now?

Yes.

> I don't want to squash all the commits of a 

When you make a few edits via the GitHub UI, it looks like this:

- update package.d
- update package.d

And maybe someone was creative and set a custom title:

- fix typo
- fix typo II

Imho you don't want such WIP commits in the main repository.

> I know this is a bikeshed problem. 

Yes. And for the record I disagree, but you have my benefit of the doubt.

**Comment by leandro-lucarella-sociomantic** [comment]
> Imho you don't want such WIP commits in the main repository.

Yes, OK, there are different styles of committing. I'm old school and would never post a PR with such kind of commits (that is not a WIP that will be cleaned up before merging) :)

**Comment by leandro-lucarella-sociomantic** [comment]
> Yes. And for the record I disagree, but you have my benefit of the doubt.

We can enable squash commits in case someone submit a PR in the WIP style you mentioned, that is safe in terms of neptune.

**Comment by leandro-lucarella-sociomantic** [comment]
Done. I re-enabled squash merges and removed the plan `auto-merge` tag, so only rebase or squash can be used. I hope that's a good balance for now!

**Comment by wilzbach** [comment]
>  I'm old school and would never post a PR with such kind of commits (that is not a WIP that will be cleaned up before merging) :)

Well, obviously you don't submit a PR like this, but it's a result of the review phase (and it does make sense to avoid squash a PR until the end, s.t. reviewers only need to catch up with the changes made and not reread the entire PR). GitHub even supports this and will only show you the commits you haven't reviewed yet.

> Donee. I re-enabled squash merges and removed the plan auto-merge tag, so only rebase or squash can be used

Thanks!

>  I hope that's a good balance for now!

Let's see how it goes ;-)

**Comment by leandro-lucarella-sociomantic** [comment]
> Well, obviously you don't submit a PR like this, but it's a result of the review phase (and it does make sense to avoid squash a PR until the end, s.t. reviewers only need to catch up with the changes made and not reread the entire PR). GitHub even supports this and will only show you the commits you haven't reviewed yet.

Yes, I know, and I use that sometimes, but there is where Git [autosquash](https://robots.thoughtbot.com/autosquashing-git-commits) shines! Just do a `git commit --fixup COMMIT` and when the PR is fully reviewed and ready, you go for a final `git rebase --autosquash` and `git push --force` and you are set!

When I first saw squash merging was available, I thought it would use `git rebase --autosquash`, but sadly it doesn't. That would be what it makes more sense (or even for rebase merges too).

**Pull request merged**
