### PR TITLE
Use automatic versioning

### PR DESCRIPTION
**Pull request by BBasile**
Like #363 but on 0.x.x

### CODE REVIEW

**Comment by BBasile** [comment]
This makefile has become horrid.

**Comment by BBasile** [comment]
It's green but the makefile require a cleanup. For example at some point `-Jbin` was added to the `INCLUDE_PATHS` variable.

**Comment by BBasile** [comment]
The original was approved

**Comment by veelo** [comment]
I fear this may be the cause of #407.

**Pull request merged**
