### PR TITLE
Replaced deprecated enforceEx with enforce

### PR DESCRIPTION
**Pull request by wilzbach**
So if I understand https://github.com/dlang-community/dfmt/issues/353 correctly I should target the lowest maintained branch (why is 0.6.x still maintained?), make the PR to it and the changes will be picked to the other branches?

Still sounds like a lot of overhead for one PR a week...

### CODE REVIEW

**Comment by Hackerpilot** [comment]
> Still sounds like a lot of overhead for one PR a week...

No kidding.

**Comment by BBasile** [comment]
This is blocked by #375. dparse update is required ASAP.

**Comment by BBasile** [comment]
I think you should target 0.x.x (master) and beaver will automatically backport when possible.

**Comment by BBasile** [comment]
sorry, i made an error, obviously i cannot change the target since this is not my PR

**Comment by wilzbach** [comment]
For future references: You should be able to change the target by clicking on "edit this PR"

**Pull request closed without merging**
