### PR TITLE
Disable osx

### PR DESCRIPTION
**Pull request by stefan-koch-sociomantic**
as requested in #311

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
I wonder if we should disable tests in ldc in appveyor too, ldc is tested by travis anyway and it just makes looking at the PR status useless...

**Comment by leandro-lucarella-sociomantic** [comment]
Or fix it, it seems to be trying to fetch a non existing file: https://github.com/ldc-developers/ldc/releases/download/v1.7.0/ldc2-1.7.0-win64-msvc.zip

But in any case leaving it when it fails consistently seems pretty pointless.

**Comment by wilzbach** [comment]
> Or fix it, it seems to be trying to fetch a non existing file:

Yes it needs this diff - https://github.com/dlang/dub/pull/1332

> I wonder if we should disable tests in ldc in appveyor too, 

I wouldn't mind. AppVeyor's slowness is annoying.
Just dmd x86 + x86_64 should be enough (+optionally ldc).

**Comment by leandro-lucarella-sociomantic** [comment]
Well, if it's reasonably slow (like an hour or so) and it works and it's a simple fix, I don't mind keeping AppVeyor.

**Comment by leandro-lucarella-sociomantic** [comment]
What's more annoying for me is the failure that makes the final github status pretty useless.

**Pull request merged**
