### PR TITLE
GIT repo change from "Hackerpilot" to "dlang-community"

### PR DESCRIPTION
**Pull request by notna123**
adopting the GIT repo change from "Hackerpilot" to "dlang-community"

### CODE REVIEW

**Comment by UplinkCoder** [comment]
Please change the commit title

**Comment by notna123** [comment]
into what?

**Comment by UplinkCoder** [comment]
Into: `Change repo-URL from "Hackerpilot" to "dlang-community"`
for example.
note you have to do this via commadline git, I don't think it can be done via the web-interface.

**Comment by notna123** [comment]
Thanks for merging, guys!

**Comment by UplinkCoder** [comment]
@BBasile You just merged a commit with the title `Update main.d`

**Comment by notna123** [comment]
yeah, was suggested by GitHub (GUI) :|

**Comment by BBasile** [comment]
Sorry Stefan but to advocate mt action: next time you can require a change explicitly. (Files -> Review -> Request change).

**Comment by BBasile** [comment]
Which was done by Brian to approve.

**Pull request merged**
