### PR TITLE
Merge remote-tracking branch 'upstream/v0.7.x' into merge-v0.8

### PR DESCRIPTION
**Pull request by wilzbach**

### CODE REVIEW

**Comment by stefan-koch-sociomantic** [comment]
please don't mess with the branches created by neptune-release manually!

**Comment by wilzbach** [comment]
But your neptune release doesn't seem to work. The release scripts weren't part of the 0.8 release!

**Comment by leandro-lucarella-sociomantic** [comment]
v0.7.1 should have been released with those changed, but it was never done. When that happens, it will be propagated to v0.8.x. I will do the release now.

**Comment by leandro-lucarella-sociomantic** [comment]
Now your fixes are in both v0.7.1 and v0.8.1. Thanks and sorry for the troubles!

**Pull request closed without merging**
