### PR TITLE
 make readme look nicer

### PR DESCRIPTION
**Pull request by dayllenger**
I got rid from that nasty horizontal scroll and polished few things.

### CODE REVIEW

**Comment by WebFreak001** [comment]
looks a bit more broken on the dub registry now but I think that should be fixed there

**Comment by dayllenger** [comment]
Hell, certainly, our main issue is that we have almost no single mature library. Like what can be simpler than markdown? If we implement it once, it will stay there and help to many people for years. We need some kind of registry, in the spirit of Rusty *arewegameyet*, *arewewebyet*, etc., to know exactly what parts of ecosystem are stable and working, and what waits to be done.

**Comment by Basile-z** [comment]
yeah current rendering is hilarious @WebFreak001. So  if this PR fixes the issue LGTM. maybe a tag is required  too.

**Comment by Basile-z** [comment]
I've just pushed a tag, let's see how the dub page looks in two hours.

**Comment by WebFreak001** [comment]
my screenshot was of a local dub instance how the PR will look on the dub registry. (so these screenshots weren't how it was looking before)

Before it looked like this:




so it's definitely not an improvement on the dub side, but I think on GitHub it does look nicer and dub should fix it instead of the dfmt README

**Comment by Basile-z** [comment]
"whoops"

**Pull request merged**
