### PR TITLE
Remove unused appveyor config

### PR DESCRIPTION
**Pull request by ibuclaw**
This is now possible now the site now has a new front for its bucket.

### CODE REVIEW

**Comment by rikkimax** [comment]
Do we use appveyor anymore?

It's not the in the checks of this PR.

**Comment by ibuclaw** [comment]
No idea, all dead pipelines and scripts should be removed for everyone's sanity. :-)

**Comment by WebFreak001** [comment]
I don't think we use appveyor, we only use GitHub Actions now.

Also why does this update the git submodules?

**Comment by ibuclaw** [comment]
> I don't think we use appveyor, we only use GitHub Actions now.
> 

OK, will delete. 


> Also why does this update the git submodules?

Maybe I didn't run submodule update?

**Comment by WebFreak001** [comment]
submodules are still modified here, updating the submodules should be a separate PR that also updates the dub.json to make the two use the same version.

**Comment by ibuclaw** [comment]
> submodules are still modified here, updating the submodules should be a separate PR that also updates the dub.json to make the two use the same version.

Again, I didn't run `submodule update`, I haven't updated the submodules locally since 2019.  Seems odd to me that GitHub includes that detail in the PR. :shrug:

**Comment by WebFreak001** [comment]
now it looks like the appveyor file is back and the submodule changes are gone still.

Try undoing your last commit and redo the whole thing and just delete the appveyor file (don't add the submouldes when committing)

**Comment by ibuclaw** [comment]
@WebFreak001 it's been years since I last used a submodule - now I remember why I never used them. :-)

**Review by WebFreak001 — APPROVED** [review]

**Pull request merged**
